# Generated by Django 4.1.2 on 2022-10-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=5)),
                ('sign', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Datos',
        ),
    ]
